### ISSUE TITLE
This is awesome. A few suggestions

### ISSUE THREAD

**Issue by WhatsNewSaes** [cktang88/word-color#1]
- Search by hitting enter would be nice
- Why not launch this as a web app?
- UI needs some love. I can help if you'd like
- click color to copy hex code would be sweet

**Comment by cktang88** [comment]
Thanks for your suggestions! I've opened two separate issues for searching w/ enter key and for copying hex code by clicking.
Also, any help on the UI would be greatly appreciated. Feel free to send pull requests.

**Comment by cktang88** [comment]
Live app is now here: https://word-color1.herokuapp.com/
